Issue 7: Support 'extends' in the SDK
OpenManufacturingPlatform/sds-sdk pull request #10
Opened 2021-09-08 10:08 UTC by georgschmidtdumont

2021-09-15 09:33 UTC, eriksven commented
This PR, assumes BAMM in version 2.0.0. Since we first want to perform a release of the SDK for BAMM 1.0.0, we will postpone the merge of this PR until the BAMM SDK for BAMM 1.0.0 has been released.

2021-11-05 10:09 UTC, atextor requested changes
LGTM, the last thing missing is the BAMM version that needs to be set to the correct 2.0.0-M1 or 2.0.0-RC1 version before merging.

2021-11-05 10:09 UTC, atextor commented on pom.xml
> +        <aspect-meta-model-version>2.0.0</aspect-meta-model-version>
As this version is not on Maven Central yet, this is the last thing blocking the PR from merging. This probably needs to be changed to "2.0.0-M1" or similar when the BAMM 2.0.0 Milestone is released.

2021-11-19 09:23 UTC, atextor approved these changes

2021-11-19 09:25 UTC, merged