Update equals method for DefaultPropertyWrapper
OpenManufacturingPlatform/sds-sdk pull request #171
Opened 2022-07-06 10:56 UTC by georgschmidtdumont

The equals method in the DefaultPropertyWrapper class did not consider
the name and urn of the property.

fixes #170

2022-07-12 06:07 UTC, atextor requested changes

2022-07-12 06:07 UTC, atextor commented on core/sds-aspect-meta-model-java/src/main/java/io/openmanufacturing/sds/metamodel/loader/DefaultPropertyWrapper.java
> +      if(o != null)
Please adhere to existing formatting

2022-07-13 05:55 UTC, DvSmi commented on core/sds-aspect-meta-model-java/src/main/java/io/openmanufacturing/sds/metamodel/loader/DefaultPropertyWrapper.java
> +      if(o != null)
Done

2022-07-13 07:42 UTC, atextor approved these changes

2022-07-13 07:43 UTC, merged