Fix bug with rendering of the "bamm:see" attributes
OpenManufacturingPlatform/sds-sdk pull request #215
Opened 2022-08-25 12:21 UTC by RaMisess

Fixes #196

2022-08-25 13:55 UTC, SteffenSta approved these changes

2022-08-25 20:56 UTC, waltersve approved these changes
Looks good

2022-09-06 12:48 UTC, atextor requested changes

2022-09-06 12:48 UTC, atextor commented on core/sds-test-aspect-models/src/main/resources/valid/bamm_2_0_0/io.openmanufacturing.test/1.0.0/AspectWithEnumOnlyOneSee.ttl
> +    bamm:name "Test";
There is no `bamm:name` in BAMM 2.0.0 any more, please remove

2022-09-07 13:03 UTC, atextor requested changes

2022-09-07 13:03 UTC, atextor commented on core/sds-test-aspect-models/src/main/resources/valid/bamm_2_0_0/io.openmanufacturing.test/1.0.0/AspectWithEnumOnlyOneSee.ttl
> +    bamm:name "prop1";
Please remove the `bamm:name` for all elements

2022-09-09 11:31 UTC, atextor approved these changes
LGTM

2022-09-09 11:57 UTC, merged